# Generated by Django 5.1 on 2024-08-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_q35ywj', upload_to='images/'),
        ),
    ]
