# Generated by Django 5.1 on 2024-08-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_joined',
        ),
    ]
