# Generated by Django 5.1 on 2024-08-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_options_remove_profile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='memorable_word',
            field=models.CharField(max_length=100),
        ),
    ]
