# Generated by Django 5.1 on 2024-08-20 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
        ('wifi_locations', '0005_alter_wifilocation_image_alter_wifilocation_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('folder_name', models.CharField(blank=True, max_length=300)),
                ('visit_status', models.CharField(choices=[('Planned', 'Planned'), ('Visited', 'Visited')], default='Planned', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wifi_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifi_locations.wifilocation')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.DeleteModel(
            name='Possibles',
        ),
    ]
