# Generated by Django 5.1 on 2024-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_locations', '0002_address_alter_wifilocation_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifilocation',
            name='image',
            field=models.ImageField(default='../default_profile_q35ywj', upload_to='images/'),
        ),
    ]
