# Generated by Django 4.2 on 2024-08-27 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wifi_locations', '0005_alter_wifilocation_image_alter_wifilocation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifilocation',
            name='address',
        ),
        migrations.AddField(
            model_name='wifilocation',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='wifilocation',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='wifilocation',
            name='postcode',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='wifilocation',
            name='street',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='added_by',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wifi_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='amenities',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
