# Generated by Django 4.2 on 2024-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_locations', '0006_remove_wifilocation_address_wifilocation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifilocation',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Australia', 'Australia'), ('South America', 'South America')], default='', max_length=50),
        ),
    ]
