# Generated by Django 4.2 on 2024-09-13 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wifi_locations', '0007_wifilocation_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifilocation',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wifi_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='amenities',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Australia', 'Australia'), ('South America', 'South America')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='postcode',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='wifilocation',
            name='street',
            field=models.CharField(max_length=150),
        ),
    ]
