# Generated by Django 5.1 on 2024-08-17 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wifi_locations', '0002_address_alter_wifilocation_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Possibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('visit_status', models.CharField(choices=[('Planned', 'Planned'), ('Visited', 'Visited')], default='Planned', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.IntegerField(choices=[(0, 'N/A'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wifi_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifi_locations.wifilocation')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
